# Generated by Django 4.1.1 on 2022-10-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('aadhar_no', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gander', models.CharField(max_length=10)),
                ('contact', models.IntegerField()),
                ('address', models.TextField(max_length=500)),
                ('clothes_color', models.CharField(max_length=100)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height_characterstics', models.CharField(max_length=50)),
                ('body_characterstics', models.CharField(max_length=50)),
                ('complexion', models.CharField(max_length=50)),
                ('hair_color', models.CharField(max_length=50)),
            ],
        ),
    ]
