# Generated by Django 4.1.1 on 2022-10-02 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_people_aadhar_no_alter_people_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='gander',
            new_name='gender',
        ),
    ]
