# Generated by Django 4.1.1 on 2022-10-03 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_peoplefound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplefound',
            name='name',
        ),
    ]
